version: 2

defaults: &defaults
    docker:
        - image: circleci/android:api-28-alpha
    working_directory: ~/code
    environment:
        _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
        TERM: dumb

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies --stacktrace
            - save_cache:
                paths:
                    - ~/.gradle
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Run Static Code Analysis
                command: ./gradlew detekt
            - run:
                name: Run Tests Staging
                command: ./gradlew testReleaseUnitTest
            - store_artifacts:
                path: app/build/reports
                destination: reports
            - store_test_results:
                path: app/build/test-results
            - run:
                name: Run Build Realease
                command: ./gradlew clean assembleRelease --stacktrace
            - store_artifacts:
                path: app/build/outputs/apk
                destination: apks
            - persist_to_workspace:
                root: .
                paths:
                    - .gradle
                    - build
                    - app/build

workflows:
    version: 2
    build_and_test:
        jobs:
            - build